# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: |
        go install github.com/nikolaydubina/go-cover-treemap@latest
        go test -v -coverprofile=coverage.out
        go-cover-treemap -coverprofile coverage.out > coverage.svg
        git config --global user.email "hola.maity@gmail.com"
        git config --global user.name "maitysubhasis"
        git add coverage.svg
        git diff-index --quiet HEAD || git commit -m "add coverage.svg"

    - name: Push changes # push the output folder to your repo
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}



